# Generated by Django 5.0.6 on 2025-07-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentattachment",
            name="mime_type",
        ),
        migrations.RemoveField(
            model_name="documentattachment",
            name="size",
        ),
    ]
