# Generated by Django 5.0.6 on 2025-07-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_documentattachment_mime_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='attachment',
            new_name='document',
        ),
    ]
