# Generated by Django 5.0.6 on 2025-07-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_attachment_signature_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='document',
            new_name='attachment',
        ),
    ]
