# Generated by Django 5.0.6 on 2025-08-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_document_signature_attachment'),
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lookups.department'),
        ),
    ]
