# Generated by Django 5.0.6 on 2025-09-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='comments_data',
            field=models.TextField(blank=True, help_text='Base64 encoded comments', null=True),
        ),
    ]
