# Generated by Django 5.0.6 on 2025-09-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_signature_comments_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('images', 'Image Files')], default='pdf', help_text='Type of files to be uploaded for this document', max_length=10),
        ),
    ]
