# Generated by Django 5.0.6 on 2025-10-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64 encoded signature', null=True),
        ),
    ]
