# Generated by Django 5.0.6 on 2025-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_signature_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentattachment',
            name='original_file',
            field=models.FileField(blank=True, help_text='Backup of original unsigned file for version management', null=True, upload_to='documents/originals/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='version_number',
            field=models.IntegerField(default=1, help_text='Signature version number, increments with each re-signature'),
        ),
    ]
