# Generated by Django 5.0.6 on 2026-01-24 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentattachment_original_file_and_more'),
        ('lookups', '0002_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='priority',
        ),
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookups.department'),
        ),
    ]
