# Generated by Django 5.0.6 on 2026-01-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_document_priority_alter_document_department'),
        ('lookups', '0002_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookups.priority'),
        ),
    ]
