# Generated by Django 5.0.6 on 2026-01-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='department_list',
            field=models.JSONField(blank=True, help_text='List of departments that will receive the document', null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
