# Generated by Django 5.0.6 on 2026-01-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_signature_department_list_signature_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='department_data',
            field=models.TextField(blank=True, help_text='Department list HTML or Base64 encoded image', null=True),
        ),
    ]

